title: קרן קלדרון
subtitle: הדרכת הורים וצוותי חינוך
phone: "+972544676633"
email: "me@kerencaldo.com"
drive: "https://drive.google.com/drive/folders/1-GpD8-yeSRp00qJh60xPNYfA_FPNOnib?usp=sharing"

instagram: "https://instagram.com/keren_caldo"
facebook: "https://www.facebook.com/pages/category/Product-Service/%D7%A7%D7%A8%D7%9F-%D7%A7%D7%9C%D7%93%D7%A8%D7%95%D7%9F-%D7%94%D7%93%D7%A8%D7%9B%D7%AA-%D7%94%D7%95%D7%A8%D7%99%D7%9D-%D7%95%D7%A6%D7%95%D7%95%D7%AA%D7%99-%D7%97%D7%99%D7%A0%D7%95%D7%9A-104759005165070/"
whatsapp: "https://api.whatsapp.com/send?phone=%{phone}&amp;text="
ganvivi: "https://www.facebook.com/gnvivi/"
cards_form: "https://forms.gle/jLL32NuNMM12MB8J7"
